-- keys/dusky-upstream.lua -- the pinned snapshot of Dusky's keybinding set.
--
-- Dusky binds these keys in .config/hypr/source/keybinds.lua. This file is data only: no
-- functions, no Hyprland API. keys/dusky-ledger.lua is checked against it,
-- so a key that appears or changes upstream is caught instead of quietly
-- missing from the port.
--
-- Regenerate after refreshing the checkout:
--   tests/lib/dusky-snapshot.sh <path-to-dusky-checkout>
--
--   repo  https://github.com/dusklinux/dusky
--   rev   47e7a113a87136b7de8f30965560d1b692e56788
--
-- Keys are kept in upstream file order. `kind` records how Dusky bound them:
-- "bind" for hl.bind, "cond" for cond_bind (Dusky's pass-through helper).

local M = {}

M.repo = "https://github.com/dusklinux/dusky"
M.rev = "47e7a113a87136b7de8f30965560d1b692e56788"
M.source = ".config/hypr/source/keybinds.lua"

M.keys = {
  { key = "ALT + SPACE", action = "Launch Menu for Apps", kind = "bind" },
  { key = "CTRL + SHIFT + SPACE", action = "Show Keybinds", kind = "bind" },
  { key = "SUPER + CTRL + SPACE", action = "Search Emojis", kind = "bind" },
  { key = "SUPER + CTRL + SHIFT + SPACE", action = "Calculator", kind = "bind" },
  { key = "SUPER + SHIFT + SPACE", action = "Matugen Theme Config", kind = "bind" },
  { key = "CTRL + SPACE", action = "Rofi Wallpaper Selector", kind = "bind" },
  { key = "SUPER + SPACE", action = "System Menu", kind = "bind" },
  { key = "CTRL + ALT + SPACE", action = "Dusky Glance", kind = "bind" },
  { key = "ALT + SHIFT + SPACE", action = "Power Menu", kind = "bind" },
  { key = "CTRL + SHIFT + escape", action = "System Monitor", kind = "bind" },
  { key = "ALT + 1", action = "Wi-Fi Manager", kind = "cond" },
  { key = "ALT + 2", action = "Bluetooth Manager", kind = "cond" },
  { key = "ALT + 3", action = "Audio Mixer", kind = "cond" },
  { key = "ALT + 4", action = "Dusky Wallpaper Selector", kind = "cond" },
  { key = "SUPER + apostrophe", action = "Cycle Next Wallpaper", kind = "bind" },
  { key = "SUPER + SHIFT + apostrophe", action = "Cycle Fav Wallpaper", kind = "bind" },
  { key = "ALT + 5", action = "Unlock Browser", kind = "cond" },
  { key = "ALT + SHIFT + 5", action = "Lock Browser", kind = "cond" },
  { key = "ALT + 6", action = "Enable Game Mode (Disable Keybinds)", kind = "cond" },
  { key = "CTRL + ALT + R", action = "Rotate Screen Clockwise", kind = "bind" },
  { key = "CTRL + ALT + SHIFT + R", action = "Rotate Screen Anti-Clockwise", kind = "bind" },
  { key = "ALT + F7", action = "Screen Off DPMS", kind = "bind" },
  { key = "ALT + F8", action = "Screen On DPMS", kind = "bind" },
  { key = "ALT + 9", action = "Start Waybar for 1 Min", kind = "cond" },
  { key = "ALT + 0", action = "system Tray TUI", kind = "cond" },
  { key = "SUPER + ALT + W", action = "Waybar Swap Configs", kind = "bind" },
  { key = "SUPER + ALT + SHIFT + W", action = "Waybar Swap Configs", kind = "bind" },
  { key = "ALT + F4", action = "Logout Menu", kind = "bind" },
  { key = "SUPER + SHIFT + R", action = "Reload Hyprland", kind = "bind" },
  { key = "ALT + V", action = "Dusky QuickPanal", kind = "cond" },
  { key = "SUPER + F", action = "Scale Up", kind = "bind" },
  { key = "SUPER + SHIFT + F", action = "Scale Down", kind = "bind" },
  { key = "SUPER + semicolon", action = "Kill Process", kind = "bind" },
  { key = "SUPER + U", action = "Key Press Sound", kind = "bind" },
  { key = "SUPER + SHIFT + U", action = "OSD KEY Presses", kind = "bind" },
  { key = "SUPER + ALT + S", action = "Shader Menu", kind = "bind" },
  { key = "SUPER + ALT + X", action = "Disable Shader", kind = "bind" },
  { key = "SUPER + ALT + V", action = "Vibrant Shader", kind = "bind" },
  { key = "SUPER + ALT + A", action = "Hyprland Animation Rofi Menu", kind = "bind" },
  { key = "SUPER + SHIFT + M", action = "Special Workspace for Spotify", kind = "bind" },
  { key = "SUPER + ALT + period", action = "Toggle Blur/Opacity", kind = "bind" },
  { key = "SUPER + period", action = "Toggle Opacity", kind = "bind" },
  { key = "SUPER + comma", action = "Toggle Per-Window Blur", kind = "bind" },
  { key = "SUPER + equal", action = "Zoom In", kind = "bind" },
  { key = "SUPER + minus", action = "Zoom Out", kind = "bind" },
  { key = "SUPER + BACKSPACE", action = "Reset Zoom", kind = "bind" },
  { key = "SUPER + SHIFT + equal", action = "Cursor Size Up", kind = "bind" },
  { key = "SUPER + SHIFT + minus", action = "Cursor Size Down", kind = "bind" },
  { key = "SUPER + SHIFT + mouse_up", action = "Cursor Size Up (Scroll)", kind = "bind" },
  { key = "SUPER + SHIFT + mouse_down", action = "Cursor Size Down (Scroll)", kind = "bind" },
  { key = "SUPER + SHIFT + BACKSPACE", action = "Cursor Size Reset", kind = "bind" },
  { key = "SUPER + V", action = "Clipboard History (Terminal)", kind = "bind" },
  { key = "SUPER + B", action = "Color Picker", kind = "bind" },
  { key = "SUPER + S", action = "Quick Screenshot", kind = "bind" },
  { key = "SHIFT + Print", action = "Full Screen Quick Screenshot", kind = "bind" },
  { key = "SUPER + SHIFT + S", action = "Screenshot and Annotation", kind = "bind" },
  { key = "Print", action = "Fullscreen Screenshot and Annotation", kind = "bind" },
  { key = "SHIFT + CTRL + ALT + space", action = "Dusky Screenshoter", kind = "bind" },
  { key = "ALT + R", action = "Screen Recorder", kind = "cond" },
  { key = "SUPER + SHIFT + G", action = "Image Search (Select and search)", kind = "bind" },
  { key = "SUPER + ALT + G", action = "Game Launcher", kind = "bind" },
  { key = "SUPER + ALT + SHIFT + G", action = "Dusky Games TUI", kind = "bind" },
  { key = "SUPER + T", action = "OCR Selection", kind = "bind" },
  { key = "SUPER + SHIFT + T", action = "OCR Fullscreen", kind = "bind" },
  { key = "SUPER + ALT + O", action = "Dusky AI LLM Side Panel", kind = "bind" },
  { key = "SUPER + ALT + M", action = "Music Recognition aka Shazam", kind = "bind" },
  { key = "SUPER + O", action = "TTS Kokoro GPU", kind = "bind" },
  { key = "SUPER + SHIFT + O", action = "TTS VC", kind = "bind" },
  { key = "SUPER + I", action = "STT Parakeet GPU", kind = "bind" },
  { key = "SUPER + N", action = "Notification History", kind = "bind" },
  { key = "SUPER + ALT + D", action = "Clear Screen Notifications", kind = "bind" },
  { key = "SUPER + ALT + F", action = "Interact with the current notification (answer Yes/No prompts)", kind = "bind" },
  { key = "SUPER + M", action = "Lock Screen", kind = "bind" },
  { key = "SUPER + C", action = "Close Window", kind = "bind" },
  { key = "SUPER + SHIFT + C", action = "Kill Focused Process Completely", kind = "bind" },
  { key = "SUPER + A", action = "Window Fullscreen", kind = "bind" },
  { key = "SUPER + SHIFT + A", action = "Window Maximize", kind = "bind" },
  { key = "SUPER + X", action = "Pin Window", kind = "bind" },
  { key = "SUPER + Y", action = "Toggle Window Split", kind = "bind" },
  { key = "SUPER + D", action = "Smart Float", kind = "bind" },
  { key = "SUPER + SHIFT + D", action = "Toggle Pseudo", kind = "bind" },
  { key = "SUPER + G", action = "Group Toggle (tabbed)", kind = "bind" },
  { key = "SUPER + ALT + H", action = "Group Prev Tab", kind = "bind" },
  { key = "SUPER + ALT + L", action = "Group Next Tab", kind = "bind" },
  { key = "SUPER + ALT + SHIFT + H", action = "Group Merge Left (create if none)", kind = "bind" },
  { key = "SUPER + ALT + SHIFT + L", action = "Group Merge Right (create if none)", kind = "bind" },
  { key = "SUPER + ALT + SHIFT + K", action = "Group Merge Up (create if none)", kind = "bind" },
  { key = "SUPER + ALT + SHIFT + J", action = "Group Merge Down (create if none)", kind = "bind" },
  { key = "SUPER + ALT + U", action = "Group Move Out (ungroup)", kind = "bind" },
  { key = "SUPER + ALT + K", action = "Group Lock Toggle", kind = "bind" },
  { key = "SUPER + h", action = "Focus Left", kind = "bind" },
  { key = "SUPER + l", action = "Focus Right", kind = "bind" },
  { key = "SUPER + k", action = "Focus Up", kind = "bind" },
  { key = "SUPER + j", action = "Focus Down", kind = "bind" },
  { key = "SUPER + SHIFT + h", action = "Move Left", kind = "bind" },
  { key = "SUPER + SHIFT + l", action = "Move Right", kind = "bind" },
  { key = "SUPER + SHIFT + k", action = "Move Up", kind = "bind" },
  { key = "SUPER + SHIFT + j", action = "Move Down", kind = "bind" },
  { key = "SUPER + right", action = "Resize Width +", kind = "bind" },
  { key = "SUPER + left", action = "Resize Width -", kind = "bind" },
  { key = "SUPER + up", action = "Resize Height -", kind = "bind" },
  { key = "SUPER + down", action = "Resize Height +", kind = "bind" },
  { key = "SUPER + TAB", action = "Last Workspace", kind = "bind" },
  { key = "ALT + SHIFT + TAB", action = "Cycle Backward", kind = "bind" },
  { key = "SUPER + SHIFT + TAB", action = "Cycle Next WS", kind = "bind" },
  { key = "SUPER + mouse_down", action = "Cycle Next Workspace", kind = "bind" },
  { key = "SUPER + mouse_up", action = "Cycle Previous Workspace", kind = "bind" },
  { key = "SUPER + Z", action = "Toggle Scratchpad", kind = "bind" },
  { key = "SUPER + SHIFT + Z", action = "Move to Scratchpad", kind = "bind" },
  { key = "SUPER + 1", action = "Switch To Context 1", kind = "bind" },
  { key = "SUPER + 2", action = "Switch To Context 2", kind = "bind" },
  { key = "SUPER + 3", action = "Switch To Context 3", kind = "bind" },
  { key = "SUPER + 4", action = "Switch To Context 4", kind = "bind" },
  { key = "SUPER + 5", action = "Switch To Context 5", kind = "bind" },
  { key = "SUPER + 6", action = "Switch To Context 6", kind = "bind" },
  { key = "SUPER + 7", action = "Switch To Context 7", kind = "bind" },
  { key = "SUPER + 8", action = "Switch To Context 8", kind = "bind" },
  { key = "SUPER + 9", action = "Switch To Context 9", kind = "bind" },
  { key = "SUPER + 0", action = "Switch To Context 10", kind = "bind" },
  { key = "SUPER + SHIFT + 1", action = "Move To Context 1", kind = "bind" },
  { key = "SUPER + SHIFT + 2", action = "Move To Context 2", kind = "bind" },
  { key = "SUPER + SHIFT + 3", action = "Move To Context 3", kind = "bind" },
  { key = "SUPER + SHIFT + 4", action = "Move To Context 4", kind = "bind" },
  { key = "SUPER + SHIFT + 5", action = "Move To Context 5", kind = "bind" },
  { key = "SUPER + SHIFT + 6", action = "Move To Context 6", kind = "bind" },
  { key = "SUPER + SHIFT + 7", action = "Move To Context 7", kind = "bind" },
  { key = "SUPER + SHIFT + 8", action = "Move To Context 8", kind = "bind" },
  { key = "SUPER + SHIFT + 9", action = "Move To Context 9", kind = "bind" },
  { key = "SUPER + SHIFT + 0", action = "Move To Context 10", kind = "bind" },
  { key = "SUPER + ALT + 1", action = "Silent Move To Context 1", kind = "bind" },
  { key = "SUPER + ALT + 2", action = "Silent Move To Context 2", kind = "bind" },
  { key = "SUPER + ALT + 3", action = "Silent Move To Context 3", kind = "bind" },
  { key = "SUPER + ALT + 4", action = "Silent Move To Context 4", kind = "bind" },
  { key = "SUPER + ALT + 5", action = "Silent Move To Context 5", kind = "bind" },
  { key = "SUPER + ALT + 6", action = "Silent Move To Context 6", kind = "bind" },
  { key = "SUPER + ALT + 7", action = "Silent Move To Context 7", kind = "bind" },
  { key = "SUPER + ALT + 8", action = "Silent Move To Context 8", kind = "bind" },
  { key = "SUPER + ALT + 9", action = "Silent Move To Context 9", kind = "bind" },
  { key = "SUPER + ALT + 0", action = "Silent Move To Context 10", kind = "bind" },
  { key = "SUPER + mouse:272", action = "Move Window", kind = "bind" },
  { key = "SUPER + mouse:273", action = "Resize Window", kind = "bind" },
  { key = "XF86AudioRaiseVolume", action = "Volume up", kind = "bind" },
  { key = "XF86AudioLowerVolume", action = "Volume down", kind = "bind" },
  { key = "XF86AudioMute", action = "Mute", kind = "bind" },
  { key = "XF86AudioMicMute", action = "Mute microphone", kind = "bind" },
  { key = "XF86MonBrightnessUp", action = "Brightness up", kind = "bind" },
  { key = "XF86MonBrightnessDown", action = "Brightness down", kind = "bind" },
  { key = "ALT + XF86AudioRaiseVolume", action = "Volume up precise", kind = "bind" },
  { key = "ALT + XF86AudioLowerVolume", action = "Volume down precise", kind = "bind" },
  { key = "ALT + XF86MonBrightnessUp", action = "Brightness up precise", kind = "bind" },
  { key = "ALT + XF86MonBrightnessDown", action = "Brightness down precise", kind = "bind" },
  { key = "XF86KbdBrightnessUp", action = "Keyboard Brightness up", kind = "bind" },
  { key = "XF86KbdBrightnessDown", action = "Keyboard Brightness down", kind = "bind" },
  { key = "SUPER + SHIFT + B", action = "Live Radio Menu", kind = "bind" },
  { key = "XF86AudioNext", action = "Next track", kind = "bind" },
  { key = "XF86AudioPrev", action = "Previous track", kind = "bind" },
  { key = "XF86AudioPlay", action = "Play", kind = "bind" },
  { key = "XF86AudioPause", action = "Pause", kind = "bind" },
  { key = "XF86AudioStop", action = "Stop", kind = "bind" },
  { key = "SUPER + P", action = "Toggle Pause", kind = "bind" },
  { key = "SUPER + SHIFT + P", action = "Toggle Audio Active Stream", kind = "bind" },
  { key = "ALT + P", action = "Mute Audio", kind = "cond" },
  { key = "ALT + M", action = "Mono Audio Toggle", kind = "cond" },
  { key = "ALT + O", action = "Switch Audio Output", kind = "cond" },
  { key = "ALT + I", action = "Switch Mic Input", kind = "cond" },
  { key = "ALT + N", action = "Dusky Audio Studio & Voice DSP", kind = "bind" },
  { key = "XF86Calculator", action = "Calculator", kind = "bind" },
}

return M
